- name: Restart mosquitto container
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain restart
  args:
    chdir: "{{ mosquitto_docker_path }}"
  changed_when: true
  listen: restart mosquitto
