---
- name: Restart mosquitto container
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain restart
    chdir: "{{ mosquitto_docker_path }}"
  changed_when: true
  listen: restart mosquitto
