---
- name: Create zigbee2mqtt deployment directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ zigbee2mqtt_docker_owner }}"
    group: "{{ zigbee2mqtt_docker_group }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ zigbee2mqtt_docker_path }}"
    - "{{ zigbee2mqtt_docker_path }}/zigbee2mqtt"

- name: Create zigbee2mqtt configuration
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: "{{ zigbee2mqtt_docker_path }}/zigbee2mqtt/configuration.yaml"
    owner: "{{ zigbee2mqtt_docker_owner }}"
    group: "{{ zigbee2mqtt_docker_group }}"
    mode: '0644'
  notify: restart zigbee2mqtt container

- name: Create zigbee2mqtt docker compose deployment
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ zigbee2mqtt_docker_path }}/compose.yaml"
    owner: "{{ zigbee2mqtt_docker_owner }}"
    group: "{{ zigbee2mqtt_docker_group }}"
    mode: '0644'
  notify: restart zigbee2mqtt container

- name: Validate zigbee2mqtt docker compose deployment
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ zigbee2mqtt_docker_path }}"
  changed_when: false

- name: Startup zigbee2mqtt docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ zigbee2mqtt_docker_path }}"
  register: _container_startup
  changed_when: "'Started' in _container_startup.stdout"
