---
- name: Create mosquitto directory
  ansible.builtin.file:
    path: "{{ mosquitto_docker_path }}"
    owner: "{{ mosquitto_docker_owner }}"
    group: "{{ mosquitto_docker_group }}"
    state: directory
    mode: '0755'

- name: Create mosquitto configuration
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto_docker_path }}/mosquitto.conf"
    mode: '0644'
  notify: restart mosquitto

- name: Create mosquitto broker credentials
  ansible.builtin.copy:
    content: "{{ mosquitto_docker_credentials }}"
    dest: "{{ mosquitto_docker_path }}/password.txt"
    mode: '0700'
  notify: restart mosquitto

- name: Create mosquitto docker compose file
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ mosquitto_docker_path }}/compose.yaml"
    owner: "{{ mosquitto_docker_owner }}"
    group: "{{ mosquitto_docker_group }}"
    trim_blocks: false
    mode: '0644'
  notify: restart mosquitto

- name: Validate mosquitto docker compose deployment
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ mosquitto_docker_path }}"
  changed_when: false

- name: Startup mosquitto docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ mosquitto_docker_path }}"
  register: _container_startup
  changed_when: "'Started' in _container_startup.stdout"
