- name: Create mosquitto directory
  ansible.builtin.file:
    path: "{{ mosquitto_docker_path }}"
    owner: "{{ mosquitto_docker_owner }}"
    group: "{{ mosquitto_docker_group }}"
    state: directory
    mode: 0755

- name: Create mosquitto configuration
  ansible.builtin.template:
    src: mosquitto.conf.j2
    dest: "{{ mosquitto_docker_path }}/mosquitto.conf"
    mode: 0644
  notify: restart mosquitto

- name: Create mosquitto broker credentials
  ansible.builtin.copy:
    content: "{{ mosquitto_docker_credentials }}"
    dest: "{{ mosquitto_docker_path }}/password.txt"
    mode: 0700
  notify: restart mosquitto

- name: Create mosquitto docker compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ mosquitto_docker_path }}/docker-compose.yml"
    owner: "{{ mosquitto_docker_owner }}"
    group: "{{ mosquitto_docker_group }}"
    trim_blocks: false
    mode: 0644
  notify: restart mosquitto

- name: Validate mosquitto docker compose deployment
  ansible.builtin.command: docker compose config --quiet
  args:
    chdir: "{{ mosquitto_docker_path }}"
  changed_when: false

- name: Startup mosquitto docker compose deployment
  ansible.builtin.command: >-
    docker compose --ansi never --progress plain up --detach
  args:
    chdir: "{{ mosquitto_docker_path }}"
  register: mosquitto_container_startup
  changed_when: "'Started' in mosquitto_container_startup.stdout"
